function transpose() 
{
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheets = ['Desktop Visits', 'MobileWeb Visits', 'Desktop Bounce Rate', 'Mobile Bounce Rate'];
  var newSheets = ['Desktop Visit', 'Mobile Visit', 'Desktop BounceRate', 'MobileWeb BounceRate'];
  for(var i=0; i<sheets.length; i++) 
  {
    var sheet = ss.getSheetByName(sheets[i]);
    sheet.setActiveCell("A40").setFormula("=transpose(A1:AB3)");
    sheet.setActiveCell("D40").setFormula("=transpose(A4:AB6)");
    sheet.setActiveCell("G40").setFormula("=transpose(A7:AB9)");  
    sheet.setActiveCell("J40").setFormula("=transpose(A10:AB12)");  
    sheet.setActiveCell("M40").setFormula("=transpose(A13:AB15)");
    sheet.setActiveCell("P40").setFormula("=transpose(A16:AB18)");
    sheet.setActiveCell("S40").setFormula("=transpose(A19:AB21)");
    sheet.setActiveCell("V40").setFormula("=transpose(A22:AB24)");
    var newSheet = ss.insertSheet(newSheets[i]);
    var country = sheet.getRange("A40").getValue(); 
    var domain = sheet.getRange("A41").getValue();
    var type = sheet.getRange("A42").getValue();
    var dates = sheet.getRange("B40:B67").getValues();
    var values = sheet.getRange("C40:C67").getValues();
    var countryRange = newSheet.getRange("A2").setValue(country);
    var typeRange = newSheet.getRange("C2").setValue(type);
    var domainRange = newSheet.getRange("B2").setValue(domain);
    var domainPaste = newSheet.getRange("B3:B29");
    domainRange.copyTo(domainPaste);
    newSheet.getRange("D2:D29").setValues(dates);
    newSheet.getRange("E2:E29").setValues(values);
    var countrya = sheet.getRange("D40").getValue(); 
    var domaina = sheet.getRange("D41").getValue();
    var typea = sheet.getRange("D42").getValue();
    var datesa = sheet.getRange("E40:E67").getValues();
    var valuesa = sheet.getRange("F40:F67").getValues();
    newSheet.getRange("A30").setValue(countrya);
    var domainRangeA = newSheet.getRange("B30").setValue(domaina);
    var domainPasteA = newSheet.getRange("B31:B57");
    domainRangeA.copyTo(domainPasteA);
    newSheet.getRange("C30").setValue(typea);
    newSheet.getRange("D30:D57").setValues(datesa);
    newSheet.getRange("E30:E57").setValues(valuesa);
    var countryb = sheet.getRange("G40").getValue(); 
    var domainb = sheet.getRange("G41").getValue();
    var typeb = sheet.getRange("G42").getValue();
    var datesb = sheet.getRange("H40:H67").getValues();
    var valuesb = sheet.getRange("I40:I67").getValues();
    newSheet.getRange("A58").setValue(countryb);
    var domainRangeB = newSheet.getRange("B58").setValue(domainb);
    var domainPasteB = newSheet.getRange("B59:B85");
    domainRangeB.copyTo(domainPasteB);
    newSheet.getRange("C58").setValue(typeb);
    newSheet.getRange("D58:D85").setValues(datesb);
    newSheet.getRange("E58:E85").setValues(valuesb);
    var countryc = sheet.getRange("J40").getValue(); 
    var domainc = sheet.getRange("J41").getValue();
    var typec = sheet.getRange("J42").getValue();
    var datesc = sheet.getRange("K40:K67").getValues();
    var valuesc = sheet.getRange("L40:L67").getValues();
    newSheet.getRange("A86").setValue(countryc);
    var domainRangeC = newSheet.getRange("B86").setValue(domainc);
    var domainPasteC = newSheet.getRange("B87:B113");
    domainRangeC.copyTo(domainPasteC);
    newSheet.getRange("C86").setValue(typec);
    newSheet.getRange("D86:D113").setValues(datesc);
    newSheet.getRange("E86:E113").setValues(valuesc);
    var countryd = sheet.getRange("M40").getValue(); 
    var domaind = sheet.getRange("M41").getValue();
    var typed = sheet.getRange("M42").getValue();
    var datesd = sheet.getRange("N40:N67").getValues();
    var valuesd = sheet.getRange("O40:O67").getValues();
    newSheet.getRange("A114").setValue(countryd);
    var domainRangeD = newSheet.getRange("B114").setValue(domaind);
    var domainPasteD = newSheet.getRange("B115:B141");
    domainRangeD.copyTo(domainPasteD);
    newSheet.getRange("C114").setValue(typed);
    newSheet.getRange("D114:D141").setValues(datesd);
    newSheet.getRange("E114:E141").setValues(valuesd);
    var countrye = sheet.getRange("P40").getValue(); 
    var domaine = sheet.getRange("P41").getValue();
    var typee = sheet.getRange("P42").getValue();
    var datese = sheet.getRange("Q40:Q67").getValues();
    var valuese = sheet.getRange("R40:R67").getValues();
    newSheet.getRange("A142").setValue(countrye);
    var domainRangeE = newSheet.getRange("B142").setValue(domaine);
    var domainPasteE = newSheet.getRange("B143:B169");
    domainRangeE.copyTo(domainPasteE);
    newSheet.getRange("C142").setValue(typee);
    newSheet.getRange("D142:D169").setValues(datese);
    newSheet.getRange("E142:E169").setValues(valuese); 
    var countryf = sheet.getRange("S40").getValue(); 
    var domainf = sheet.getRange("S41").getValue();
    var typef = sheet.getRange("S42").getValue();
    var datesf = sheet.getRange("T40:T67").getValues();
    var valuesf = sheet.getRange("U40:U67").getValues();
    newSheet.getRange("A170").setValue(countryf);
    var domainRangeF = newSheet.getRange("B170").setValue(domainf);
    var domainPasteF = newSheet.getRange("B171:B197");
    domainRangeF.copyTo(domainPasteF);
    newSheet.getRange("C170").setValue(typef);
    newSheet.getRange("D170:D197").setValues(datesf);
    newSheet.getRange("E170:E197").setValues(valuesf); 
    var countryg = sheet.getRange("V40").getValue(); 
    var domaing = sheet.getRange("V41").getValue();
    var typeg = sheet.getRange("V42").getValue();
    var datesg = sheet.getRange("W40:W67").getValues();
    var valuesg = sheet.getRange("X40:X67").getValues();
    newSheet.getRange("A198").setValue(countryg);
    var domainRangeG = newSheet.getRange("B198").setValue(domaing);
    var domainPasteG = newSheet.getRange("B199:B225");
    domainRangeG.copyTo(domainPasteG);
    newSheet.getRange("C198").setValue(typeg);
    newSheet.getRange("D198:D225").setValues(datesg);
    newSheet.getRange("E198:E225").setValues(valuesg); 
    var clear = newSheet.getRange("A3:A225");
    clear.clearContent();
    var countryPaste = newSheet.getRange("A3:A225");
    countryRange.copyTo(countryPaste);
    var clearagain = newSheet.getRange("C3:C225");
    clearagain.clearContent();
    var typePaste = newSheet.getRange("C3:C225");
    typeRange.copyTo(typePaste);  
  }
}

function transposeMAU() 
{
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheets = ['Desktop MAU', 'MobileWeb MAU'];
  var newSheets = ['DesktopMAU', 'Mobile MAU'];
  for(var i=0; i<sheets.length; i++) 
  {
    var sheet = ss.getSheetByName(sheets[i]);
    sheet.setActiveCell("A40").setFormula("=transpose(A1:M3)");
    sheet.setActiveCell("D40").setFormula("=transpose(A4:M6)");
    sheet.setActiveCell("G40").setFormula("=transpose(A7:M9)");  
    sheet.setActiveCell("J40").setFormula("=transpose(A10:M12)");  
    sheet.setActiveCell("M40").setFormula("=transpose(A13:M15)");
    sheet.setActiveCell("P40").setFormula("=transpose(A16:M18)");
    sheet.setActiveCell("S40").setFormula("=transpose(A19:M21)");
    sheet.setActiveCell("V40").setFormula("=transpose(A22:M24)");
    var newSheet = ss.insertSheet(newSheets[i]);
    var country = sheet.getRange("A40").getValue(); 
    var domain = sheet.getRange("A41").getValue();
    var type = sheet.getRange("A42").getValue();
    var dates = sheet.getRange("B40:B52").getValues();
    var values = sheet.getRange("C40:C52").getValues();
    var countryRange = newSheet.getRange("A2").setValue(country);
    var typeRange = newSheet.getRange("C2").setValue(type);
    var domainRange = newSheet.getRange("B2").setValue(domain);
    var domainPaste = newSheet.getRange("B3:B14");
    domainRange.copyTo(domainPaste);
    newSheet.getRange("D2:D14").setValues(dates);
    newSheet.getRange("E2:E14").setValues(values);
    var countrya = sheet.getRange("D40").getValue(); 
    var domaina = sheet.getRange("D41").getValue();
    var typea = sheet.getRange("D42").getValue();
    var datesa = sheet.getRange("E40:E52").getValues();
    var valuesa = sheet.getRange("F40:F52").getValues();
    newSheet.getRange("A15").setValue(countrya);
    var domainRangeA = newSheet.getRange("B15").setValue(domaina);
    var domainPasteA = newSheet.getRange("B16:B27");
    domainRangeA.copyTo(domainPasteA);
    newSheet.getRange("C15").setValue(typea);
    newSheet.getRange("D15:D27").setValues(datesa);
    newSheet.getRange("E15:E27").setValues(valuesa);
    var countryb = sheet.getRange("G40").getValue(); 
    var domainb = sheet.getRange("G41").getValue();
    var typeb = sheet.getRange("G42").getValue();
    var datesb = sheet.getRange("H40:H52").getValues();
    var valuesb = sheet.getRange("I40:I52").getValues();
    newSheet.getRange("A28").setValue(countryb);
    var domainRangeB = newSheet.getRange("B28").setValue(domainb);
    var domainPasteB = newSheet.getRange("B29:B40");
    domainRangeB.copyTo(domainPasteB);
    newSheet.getRange("C28").setValue(typeb);
    newSheet.getRange("D28:D40").setValues(datesb);
    newSheet.getRange("E28:E40").setValues(valuesb);
    var countryc = sheet.getRange("J40").getValue(); 
    var domainc = sheet.getRange("J41").getValue();
    var typec = sheet.getRange("J42").getValue();
    var datesc = sheet.getRange("K40:K52").getValues();
    var valuesc = sheet.getRange("L40:L52").getValues();
    newSheet.getRange("A41").setValue(countryc);
    var domainRangeC = newSheet.getRange("B41").setValue(domainc);
    var domainPasteC = newSheet.getRange("B42:B53");
    domainRangeC.copyTo(domainPasteC);
    newSheet.getRange("C41").setValue(typec);
    newSheet.getRange("D41:D53").setValues(datesc);
    newSheet.getRange("E41:E53").setValues(valuesc);
    var countryd = sheet.getRange("M40").getValue(); 
    var domaind = sheet.getRange("M41").getValue();
    var typed = sheet.getRange("M42").getValue();
    var datesd = sheet.getRange("N40:N52").getValues();
    var valuesd = sheet.getRange("O40:O52").getValues();
    newSheet.getRange("A54").setValue(countryd);
    var domainRangeD = newSheet.getRange("B54").setValue(domaind);
    var domainPasteD = newSheet.getRange("B55:B66");
    domainRangeD.copyTo(domainPasteD);
    newSheet.getRange("C54").setValue(typed);
    newSheet.getRange("D54:D66").setValues(datesd);
    newSheet.getRange("E54:E66").setValues(valuesd);
    var countrye = sheet.getRange("P40").getValue(); 
    var domaine = sheet.getRange("P41").getValue();
    var typee = sheet.getRange("P42").getValue();
    var datese = sheet.getRange("Q40:Q52").getValues();
    var valuese = sheet.getRange("R40:R52").getValues();
    newSheet.getRange("A67").setValue(countrye);
    var domainRangeE = newSheet.getRange("B67").setValue(domaine);
    var domainPasteE = newSheet.getRange("B68:B79");
    domainRangeE.copyTo(domainPasteE);
    newSheet.getRange("C67").setValue(typee);
    newSheet.getRange("D67:D79").setValues(datese);
    newSheet.getRange("E67:E79").setValues(valuese); 
    var countryf = sheet.getRange("S40").getValue(); 
    var domainf = sheet.getRange("S41").getValue();
    var typef = sheet.getRange("S42").getValue();
    var datesf = sheet.getRange("T40:T52").getValues();
    var valuesf = sheet.getRange("U40:U52").getValues();
    newSheet.getRange("A80").setValue(countryf);
    var domainRangeF = newSheet.getRange("B80").setValue(domainf);
    var domainPasteF = newSheet.getRange("B81:B92");
    domainRangeF.copyTo(domainPasteF);
    newSheet.getRange("C80").setValue(typef);
    newSheet.getRange("D80:D92").setValues(datesf);
    newSheet.getRange("E80:E92").setValues(valuesf); 
    var countryg = sheet.getRange("V40").getValue(); 
    var domaing = sheet.getRange("V41").getValue();
    var typeg = sheet.getRange("V42").getValue();
    var datesg = sheet.getRange("W40:W52").getValues();
    var valuesg = sheet.getRange("X40:X52").getValues();
    newSheet.getRange("A93").setValue(countryg);
    var domainRangeG = newSheet.getRange("B93").setValue(domaing);
    var domainPasteG = newSheet.getRange("B94:B105");
    domainRangeG.copyTo(domainPasteG);
    newSheet.getRange("C93").setValue(typeg);
    newSheet.getRange("D93:D105").setValues(datesg);
    newSheet.getRange("E93:E105").setValues(valuesg); 
    var clear = newSheet.getRange("A3:A105");
    clear.clearContent();
    var countryPaste = newSheet.getRange("A3:A105");
    countryRange.copyTo(countryPaste);
    var clearagain = newSheet.getRange("C3:C105");
    clearagain.clearContent();
    var typePaste = newSheet.getRange("C3:C105");
    typeRange.copyTo(typePaste);
  }  
}



